export const SHEET_IDS = {
  CHARACTER_ALL: 0,
  CHARACTER_YUFU: 1,
  CHARACTER_KUROKAMI: 2,
  CHARACTER_MOCHI: 3,
  CHARACTER_KAWABE: 4,
  CHARACTER_SAINT: 5,
  CHARACTER_HORAGAI: 6,
  LOGS: 7,
  COOK: 8,
  MATERIAL: 10,
} as const;
